spring.application.name=DocuMind


##disable the autoconfig
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

com.sachin.URL = https://api.chatanywhere.tech/v1
com.sachin.Token = sk-ZOkS8PHxTgO8AL3BSvK1PlGNzJgJ2aTAB5B1Gt8iuJOnVi8q
